export const khdaMapping = {
  dataSourceId: "Educationcenterid",
  name: "Name_eng",
  nameAr: "Name_ar",
  area: "Areaen",
  areaAr: "Areaar",
  address: "Address",
  addressAr: "Addressar",
  latitude: "Lat",
  longitude: "Long",
  email: "Email",
  phone: "Telephone",
  mobile: "Mobile",
  website: "Web_address",
  curriculum: "Curriculumen",
  curriculumAr: "Curriculumar",
  inspectionRating: "Overallperformanceen",
  inspectionRatingAr: "Overallperformancear",
  inspectionYear: "Inspectionyear",
  inspectionReportUrl: "Inspectionreportpdflinken",
  heroImageUrl: "Imagelargeurl",
  establishedOn: "Establishedon",
  loadTimestamp: "Load_timestamp",
  studentCount: "Studentcount",
  poBox: "Pobox",
};