export const heecoMatchQuestions = [
  {
    id: "emirate",
    type: "single-choice",
    step: 1,
    title: "Where are you looking for a school?",
    options: [
      { id: "dubai", label: "Dubai" },
      { id: "sharjah", label: "Sharjah" },
      { id: "abu-dhabi", label: "Abu Dhabi" },
      { id: "ajman", label: "Ajman" },
    ],
  },
  {
    id: "curriculum",
    type: "single-choice",
    step: 2,
    title: "Which curriculum do you prefer?",
    options: [
  { id: "British", label: "British" },
  { id: "CBSE", label: "CBSE" },
  { id: "American", label: "American" },
  { id: "IB", label: "IB" },
  { id: "No Preference", label: "No Preference" },
],
  },
  {
    id: "grade",
    type: "single-choice",
    step: 3,
    title: "Which grade are you applying for?",
   options: [
  { id: "KG1", label: "KG1" },
  { id: "KG2", label: "KG2" },
  { id: "Grade 1", label: "Grade 1" },
  { id: "Grade 2", label: "Grade 2" },
  { id: "Grade 3", label: "Grade 3" },
  { id: "Grade 4", label: "Grade 4" },
  { id: "Grade 5", label: "Grade 5" },
  { id: "Grade 6", label: "Grade 6" },
  { id: "Grade 7", label: "Grade 7" },
  { id: "Grade 8", label: "Grade 8" },
  { id: "Grade 9", label: "Grade 9" },
  { id: "Grade 10", label: "Grade 10" },
  { id: "Grade 11", label: "Grade 11" },
  { id: "Grade 12", label: "Grade 12" },
],
  },
  {
    id: "budget",
    type: "single-choice",
    step: 4,
    title: "What is your annual tuition budget?",
    options: [
      { id: "below-20k", label: "Below AED 20,000" },
      { id: "20k-40k", label: "AED 20,000 - 40,000" },
      { id: "40k-60k", label: "AED 40,000 - 60,000" },
      { id: "above-60k", label: "Above AED 60,000" },
    ],
  },
  
  {
    id: "priority",
    type: "single-choice",
    step: 5,
    title: "What matters most to you?",
   options: [
  { id: "Academic focus", label: "Academic Focus" },
  { id: "Affordable fees", label: "Affordable Fees" },
  { id: "Sports", label: "Sports & Activities" },
  { id: "STEM", label: "STEM / Innovation" },
  { id: "Career exposure", label: "Career Exposure" },
  { id: "Industrial visits", label: "Industrial Visits" },
],
  },
];
export const cbseGradeOptions = [
  { id: "KG1", label: "KG1" },
  { id: "KG2", label: "KG2" },
  { id: "Grade 1", label: "Grade 1" },
  { id: "Grade 2", label: "Grade 2" },
  { id: "Grade 3", label: "Grade 3" },
  { id: "Grade 4", label: "Grade 4" },
  { id: "Grade 5", label: "Grade 5" },
  { id: "Grade 6", label: "Grade 6" },
  { id: "Grade 7", label: "Grade 7" },
  { id: "Grade 8", label: "Grade 8" },
  { id: "Grade 9", label: "Grade 9" },
  { id: "Grade 10", label: "Grade 10" },
  { id: "Grade 11", label: "Grade 11" },
  { id: "Grade 12", label: "Grade 12" },
];

export const britishGradeOptions = [
  { id: "FS1", label: "FS1" },
  { id: "FS2", label: "FS2" },
  { id: "Year 1", label: "Year 1" },
  { id: "Year 2", label: "Year 2" },
  { id: "Year 3", label: "Year 3" },
  { id: "Year 4", label: "Year 4" },
  { id: "Year 5", label: "Year 5" },
  { id: "Year 6", label: "Year 6" },
  { id: "Year 7", label: "Year 7" },
  { id: "Year 8", label: "Year 8" },
  { id: "Year 9", label: "Year 9" },
  { id: "Year 10", label: "Year 10" },
  { id: "Year 11", label: "Year 11" },
  { id: "Year 12", label: "Year 12" },
  { id: "Year 13", label: "Year 13" },
];

export const americanGradeOptions = [
  { id: "KG", label: "KG" },
  { id: "Grade 1", label: "Grade 1" },
  { id: "Grade 2", label: "Grade 2" },
  { id: "Grade 3", label: "Grade 3" },
  { id: "Grade 4", label: "Grade 4" },
  { id: "Grade 5", label: "Grade 5" },
  { id: "Grade 6", label: "Grade 6" },
  { id: "Grade 7", label: "Grade 7" },
  { id: "Grade 8", label: "Grade 8" },
  { id: "Grade 9", label: "Grade 9" },
  { id: "Grade 10", label: "Grade 10" },
  { id: "Grade 11", label: "Grade 11" },
  { id: "Grade 12", label: "Grade 12" },
];

export const ibGradeOptions = [
  { id: "PYP", label: "PYP" },
  { id: "MYP", label: "MYP" },
  { id: "DP", label: "DP" },
];